version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:Saydaliyev0512@postgres-db:5432/otp-api?schema=public
    command:
      ['./wait-for-postgres.sh', 'postgres-db', 'npm', 'run', 'start:prod']

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saydaliyev0512
      POSTGRES_DB: otp-api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
